services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  fast_app:
    image: fast_app
    entrypoint: ./docker/entrypoint.sh
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - fast
    env_file:
      - .env.local

volumes:
  pgdata:
